export const tokens = {
  USER_MODEL: 'USER_MODEL',
  NOTE_MODEL: 'NOTE_MODEL',
  USER_SERVICE: 'USER_SERVICE',
  NOTE_SERVICE: 'NOTE_SERVICE',
  EMAIL_PROVIDER: 'EMAIL_PROVIDER',
  EMAIL_SERVICE: 'EMAIL_SERVICE',
  FOCUSTIME_MODEL: 'FOCUSTIME_MODEL',
  FOCUSTIME_SERVICE: 'FOCUSTIME_SERVICE',
  GOAL_MODEL: 'GOAL_MODEL',
};
